# Example JsonServer - Basic example
apiVersion: example.com/v1
kind: JsonServer
metadata:
  name: app-my-server
  namespace: default
spec:
  replicas: 2
  jsonConfig: |
    {
      "people": [
        {
          "id": 1,
          "name": "Person A"
        },
        {
          "id": 2,
          "name": "Person B"
        }
      ]
    }
